# Generated by Django 3.2.11 on 2022-01-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_order_id_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='orderNumber',
        ),
    ]
